const initialUnits=[
{id:'A52',name:'A52',agency:'MCSO',type:'Patrol',tab:'available',status:'ACTIVE',address:'120 Main St',shift:'Started 38 min ago',crew:'523 J. Miller',vehicle:'Unit 52',fallback:'AVAILABLE',stripe:'#60a5fa',gradient:'rgba(96,165,250,.26)',hq:true},
{id:'B25',name:'B25',agency:'MCSO',type:'Patrol',tab:'available',status:'ACTIVE',address:'85 Church Ave',shift:'Started 29 min ago',crew:'411 A. Torres',vehicle:'Unit 25',fallback:'AVAILABLE',stripe:'#60a5fa',gradient:'rgba(96,165,250,.26)',hq:true},
{id:'1001',name:'1001 – Police Car',agency:'MPD',type:'Patrol',tab:'available',status:'ACTIVE',address:'300 Broadway',shift:'Started 42 min ago',crew:'291 D. Carter',vehicle:'Police Car 1001',fallback:'AVAILABLE',stripe:'#60a5fa',gradient:'rgba(96,165,250,.26)',hq:true},
{id:'1002',name:'1002 – Fire Truck',agency:'MFD',type:'Fire',tab:'available',status:'ACTIVE',address:'Fire Station 1',shift:'Started 16 min ago',crew:'F12 R. Evans',vehicle:'Engine 1002',fallback:'STANDBY',stripe:'#f59e0b',gradient:'rgba(245,158,11,.24)',standby:true},
{id:'FL004',name:'FL 004',agency:'MFD',type:'Fire',tab:'assigned',status:'ASSIGNED',address:'440 9th St',shift:'Started 1 hr ago',crew:'F18 S. Lewis',vehicle:'Truck 4',fallback:'STANDBY',cfs:'CFS2507027',stripe:'#f59e0b',gradient:'rgba(245,158,11,.24)'},
{id:'FL008',name:'FL 008',agency:'MFD',type:'Fire',tab:'assigned',status:'ON_SCENE',address:'440 9th St',shift:'Started 54 min ago',crew:'F22 N. Green',vehicle:'Engine 8',fallback:'STANDBY',cfs:'CFS2507027',stripe:'#f59e0b',gradient:'rgba(245,158,11,.24)'}
];
let units=initialUnits.map(x=>({...x}));
let state={tab:'available',context:'details',expanded:new Set(),groups:{},drag:null,search:'',logs:[]};
const $=s=>document.querySelector(s), list=$('#units-list'), toast=$('#toast'), tabs=$('#unit-tabs'), statusFilter=$('#status-filter');
const get=id=>units.find(u=>u.id===id);const parentOf=id=>Object.entries(state.groups).find(([,v])=>v.includes(id))?.[0]||null;const rootOf=id=>parentOf(id)||id;
const statusLabel=s=>({ACTIVE:'Active',QUEUED:'Queued',ASSIGNED:'Assigned',EN_ROUTE:'En Route',ON_SCENE:'On Scene',IN_THE_AREA:'In the Area',PROGRESS:'In Progress',STANDBY:'Standby'})[s]||s;
function effective(child,parent){return {...child,status:parent.status,cfs:parent.cfs,address:parent.address}}
function log(message){state.logs.unshift({message,time:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})});renderLogs()}
function notify(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(notify.t);notify.t=setTimeout(()=>toast.classList.remove('show'),2200)}
function fieldRows(u){return `${u.cfs?`<dt>Call</dt><dd>${u.cfs}</dd>`:''}${u.shift?`<dt>Shift</dt><dd>${u.shift}</dd>`:''}${u.standby?'<dt>Standby</dt><dd>Available when off duty</dd>':''}${u.crew?`<dt>Crew</dt><dd>${u.crew}</dd>`:''}${u.vehicle?`<dt>Vehicles</dt><dd>${u.vehicle}</dd>`:''}`}
function badge(u){return `<span class="status-badge status-${u.status}">${statusLabel(u.status)}</span>`}
function activeActions(u){return `<div class="action-row"><button class="btn-xs ghost left">Edit resources</button><button class="btn-xs ghost" data-action="off" data-id="${u.id}">Set Off Duty</button>${u.hq?`<button class="btn-xs ghost">Assign to HQ</button>`:''}<button class="btn-xs" data-action="assign" data-id="${u.id}">Assign to CFS</button></div>`}
const steps=[['ASSIGNED','Assigned'],['EN_ROUTE','En Route'],['IN_THE_AREA','In The Area'],['ON_SCENE','On Scene'],['PROGRESS','In Progress']];
function assignedActions(u){const idx=Math.max(0,steps.findIndex(([s])=>s===u.status));return `<div class="stepper-wrap"><div class="stepper">${steps.map(([s,l],i)=>`<button class="${i===idx?'current':i<idx?'past':''}" data-action="status" data-id="${u.id}" data-status="${s}">${l}</button>`).join('')}</div><div class="fade-divider"></div><div class="action-row"><button class="btn-xs ghost left">Edit resources</button><button class="btn-xs ghost">Cancel</button><button class="btn-xs">Complete</button></div></div>`}
function expandedSub(child,parent){const e=effective(child,parent);return `<div class="expanded-subunit"><div class="sub-head"><span class="corner">↳</span><div class="sub-main"><div class="sub-title-row"><span class="sub-title">${child.name}</span>${badge(e)}</div><p class="follows">Follows ${parent.name}</p></div></div><dl class="unit-fields">${fieldRows(e)}</dl><button class="outline-full" data-action="ungroup-one" data-id="${child.id}">Ungroup unit</button></div>`}
function card(u){const children=(state.groups[u.id]||[]).map(get).filter(Boolean), open=state.expanded.has(u.id);return `<div class="unit-item ${open?'selected':''}" draggable="true" data-id="${u.id}" style="--stripe:${u.stripe};--gradient:${u.gradient}"><button class="unit-header" data-action="toggle" data-id="${u.id}"><div class="row-summary"><div class="row-top"><span class="unit-name">${u.name}<span class="unit-meta"> · ${u.agency} · ${u.type}</span></span>${badge(u)}</div><p class="unit-address">${u.address||'Offline'}</p></div><span class="chevron">⌄</span></button>${children.length&&!open?`<div class="collapsed-group"><div class="collapsed-group-title"><span>↳</span> Group · ${children.length+1} units</div>${children.map(c=>{const e=effective(c,u);return `<div class="compact-sub-row"><span class="compact-name">${c.name}</span><span class="compact-type">${c.type}</span>${badge(e)}</div>`}).join('')}</div>`:''}<div class="unit-expanded"><div class="fields-block"><dl class="unit-fields">${fieldRows(u)}</dl></div><div class="fade-divider"></div><div class="actions-pad">${u.tab==='available'?activeActions(u):assignedActions(u)}${children.length?`<button class="outline-full" data-action="ungroup-all" data-id="${u.id}">Ungroup all</button>`:''}</div>${children.length?`<div class="expanded-subunits"><div class="expanded-subunits-title">Sub-units · controlled by ${u.name}</div>${children.map(c=>expandedSub(c,u)).join('')}</div>`:''}</div></div>`}
function visible(){const q=state.search.trim().toLowerCase();return units.filter(u=>u.tab===state.tab&&!parentOf(u.id)).filter(u=>!q||[u.name,u.agency,u.type,u.address,u.status].join(' ').toLowerCase().includes(q))}
function render(){const roots=visible();list.innerHTML=roots.length?roots.map(u=>`<div class="unit-group">${card(u)}</div>`).join(''):'<div class="empty-state">No units</div>';$('#available-count').textContent=units.filter(u=>u.tab==='available'&&!parentOf(u.id)).length;$('#assigned-count').textContent=units.filter(u=>u.tab==='assigned'&&!parentOf(u.id)).length;tabs.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));statusFilter.innerHTML=(state.tab==='available'?['All','Active']:['All','Assigned','En Route','In The Area','On Scene','In Progress']).map((x,i)=>`<button class="status-chip ${i===0?'active':''}">${x}</button>`).join('');wireDrag()}
function wireDrag(){list.querySelectorAll('.unit-item').forEach(el=>{el.addEventListener('dragstart',e=>{state.drag=el.dataset.id;el.classList.add('dragging');$('#drag-message').hidden=false;e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',state.drag)});el.addEventListener('dragend',()=>{state.drag=null;$('#drag-message').hidden=true;document.querySelectorAll('.dragging,.drop-target').forEach(x=>x.classList.remove('dragging','drop-target'))});el.addEventListener('dragover',e=>{if(!state.drag||state.drag===el.dataset.id)return;e.preventDefault();el.classList.add('drop-target')});el.addEventListener('dragleave',()=>el.classList.remove('drop-target'));el.addEventListener('drop',e=>{e.preventDefault();el.classList.remove('drop-target');const dragged=state.drag||e.dataTransfer.getData('text/plain');if(dragged&&dragged!==el.dataset.id)group(dragged,el.dataset.id)})})}
function group(dragged,target){const top=rootOf(target);if(top===dragged)return;const old=parentOf(dragged);if(old){state.groups[old]=state.groups[old].filter(x=>x!==dragged);if(!state.groups[old].length)delete state.groups[old]}const nested=[...(state.groups[dragged]||[])];delete state.groups[dragged];state.groups[top]??=[];[dragged,...nested].forEach(id=>{if(id!==top&&!state.groups[top].includes(id))state.groups[top].push(id);const c=get(id),p=get(top);c.tab=p.tab;c.status=p.status;c.address=p.address;c.cfs=p.cfs});state.expanded.delete(top);log(`${get(top).name} grouped with ${get(dragged).name}`);notify(`${get(dragged).name} is now a sub-unit of ${get(top).name}.`);render()}
function members(root){return [root,...(state.groups[root]||[])]}
function applyStatus(id,status){const root=rootOf(id), p=get(root);members(root).forEach(mid=>{const u=get(mid);u.status=status;u.tab='assigned';u.cfs='CFS2507027';u.address='440 9th St'});log(`${p.name} group → ${statusLabel(status)}`);render()}
function assign(id){const root=rootOf(id),p=get(root),subs=state.groups[root]||[];members(root).forEach(mid=>{const u=get(mid);u.tab='assigned';u.status='ASSIGNED';u.cfs='CFS2507027';u.address='440 9th St'});state.tab='assigned';log(subs.length?`${p.name} with sub-unit ${subs.map(x=>get(x).name).join(', ')} was assigned to CFS2507027`:`${p.name} was assigned to CFS2507027`);render()}
function fallback(u){if(u.fallback==='STANDBY'){u.tab='available';u.status='STANDBY';u.address='Fire Station 1';delete u.cfs}else{u.tab='available';u.status='ACTIVE';delete u.cfs}}
function ungroupOne(id){const parent=parentOf(id);if(!parent)return;state.groups[parent]=state.groups[parent].filter(x=>x!==id);if(!state.groups[parent].length)delete state.groups[parent];fallback(get(id));log(`${get(id).name} ungrouped`);render()}
function ungroupAll(id){const subs=[...(state.groups[id]||[])];subs.forEach(s=>fallback(get(s)));delete state.groups[id];log(`${get(id).name} group ungrouped`);render()}
function closeCfs(){units.filter(u=>u.tab==='assigned'&&!parentOf(u.id)).forEach(p=>members(p.id).forEach(mid=>{const u=get(mid);u.tab='available';u.status='ACTIVE';delete u.cfs;if(u.id==='1002')u.address='Fire Station 1'}));state.tab='available';log('CFS2507027 closed — grouped units moved together to Available');render()}
function renderLogs(){$('#log-list').innerHTML=state.logs.length?state.logs.map(x=>`<div class="log-row"><strong>${x.message}</strong>${x.time}</div>`).join(''):'<div class="log-row">No events yet</div>'}
list.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const {action,id,status}=b.dataset;if(action==='toggle'){state.expanded.has(id)?state.expanded.delete(id):state.expanded.add(id);render()}else if(action==='assign')assign(id);else if(action==='status')applyStatus(id,status);else if(action==='ungroup-one')ungroupOne(id);else if(action==='ungroup-all')ungroupAll(id);else if(action==='off'){get(id).status='STANDBY';render()}});tabs.addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(!b)return;state.tab=b.dataset.tab;render()});$('#unit-search').addEventListener('input',e=>{state.search=e.target.value;render()});$('#close-cfs').addEventListener('click',closeCfs);$('#reset-demo').addEventListener('click',()=>{units=initialUnits.map(x=>({...x}));state={...state,tab:'available',expanded:new Set(),groups:{},drag:null,search:'',logs:[]};$('#unit-search').value='';renderLogs();render()});$('#context-switch').addEventListener('click',e=>{const b=e.target.closest('[data-context]');if(!b)return;state.context=b.dataset.context;$('#context-switch').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b))});renderLogs();render();
