const BASE_UNITS = [
  {id:'A52',name:'A52',agency:'MCSO',type:'Patrol',agencyType:'POLICE',tab:'available',status:'ACTIVE',address:'120 Main St',shift:'Started 38 min ago',crew:['523 J. Miller'],vehicles:['Unit 52'],fallback:'AVAILABLE'},
  {id:'B25',name:'B25',agency:'MCSO',type:'Patrol',agencyType:'POLICE',tab:'available',status:'ACTIVE',address:'85 Church Ave',shift:'Started 42 min ago',crew:['411 A. Torres'],vehicles:['Unit 25'],fallback:'AVAILABLE'},
  {id:'1001',name:'1001 – Police Car',agency:'MPD',type:'Patrol',agencyType:'POLICE',tab:'available',status:'ACTIVE',address:'300 Broadway',shift:'Started 1 hr ago',crew:['291 D. Carter'],vehicles:['Police Car 1001'],fallback:'AVAILABLE'},
  {id:'1002',name:'1002 – Fire Truck',agency:'MFD',type:'Fire',agencyType:'FIRE',tab:'available',status:'ACTIVE',address:'Fire Station 1',shift:'Started 54 min ago',crew:['F12 R. Evans'],vehicles:['Engine 1002'],fallback:'STANDBY',standby:true},
  {id:'FL004',name:'FL 004',agency:'MFD',type:'Fire',agencyType:'FIRE',tab:'assigned',status:'ASSIGNED',address:'440 9th St',shift:'Started 1 hr ago',crew:['F18 S. Lewis'],vehicles:['Truck 4'],fallback:'STANDBY',cfs:'CFS2507027'},
  {id:'FL008',name:'FL 008',agency:'MFD',type:'Fire',agencyType:'FIRE',tab:'assigned',status:'ON_SCENE',address:'440 9th St',shift:'Started 54 min ago',crew:['F22 N. Green'],vehicles:['Engine 8'],fallback:'STANDBY',cfs:'CFS2507027'},
  {id:'K911',name:'K9 11',agency:'MCSO',type:'K9',agencyType:'SHERIFF',tab:'assigned',status:'EN_ROUTE',address:'440 9th St',shift:'Started 47 min ago',crew:['K11 P. Stone'],vehicles:['K9 11'],fallback:'AVAILABLE',cfs:'CFS2507027'}
];
let units=BASE_UNITS.map(u=>({...u,crew:[...u.crew],vehicles:[...u.vehicles]}));
const state={tab:'available',selectedId:null,groups:{},dragId:null,search:'',agency:'all',assignedFilter:'ALL'};
const els={list:document.querySelector('#units-list'),tabs:document.querySelector('#unit-tabs'),dot:document.querySelector('#active-dot'),search:document.querySelector('#unit-search'),substatus:document.querySelector('#substatus-wrap'),toast:document.querySelector('#toast'),filterTrigger:document.querySelector('#filter-trigger'),filterPopover:document.querySelector('#filters-popover'),filterCount:document.querySelector('#filter-count')};
const STATUS_LABEL={ACTIVE:'Active',QUEUED:'Queued',ASSIGNED:'Assigned',EN_ROUTE:'En Route',ON_SCENE:'On Scene',IN_THE_AREA:'In the Area',PROGRESS:'In Progress',STANDBY:'Standby',OFF_DUTY:'Off Duty'};
const ASSIGN_STEPS=[['ASSIGNED','Assigned'],['EN_ROUTE','En Route'],['ON_SCENE','On Scene'],['IN_THE_AREA','In Area'],['PROGRESS','In Progress']];
function unit(id){return units.find(u=>u.id===id)}
function parentOf(id){for(const [top,subs] of Object.entries(state.groups))if(subs.includes(id))return top;return null}
function rootOf(id){return parentOf(id)||id}
function members(root){return [root,...(state.groups[root]||[])]}
function showToast(message){els.toast.textContent=message;els.toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>els.toast.classList.remove('show'),2200)}
function audit(message){console.info(`[Unit grouping] ${message}`)}
function visibleRoots(){const q=state.search.trim().toLowerCase();return units.filter(u=>u.tab===state.tab&&!parentOf(u.id)).filter(u=>state.agency==='all'||u.agencyType===state.agency).filter(u=>state.tab!=='assigned'||state.assignedFilter==='ALL'||u.status===state.assignedFilter).filter(u=>!q||[u.name,u.agency,u.type,u.address,u.status].join(' ').toLowerCase().includes(q))}
function chevron(){return '<svg class="chevron" viewBox="0 0 24 24" aria-hidden="true"><path d="m6 9 6 6 6-6"></path></svg>'}
function statusBadge(u){return `<span class="status-badge status-${u.status}">${STATUS_LABEL[u.status]||u.status}</span>`}
function fields(u){return `<div class="fields-pad"><dl class="unit-fields">${u.cfs?`<dt>Call</dt><dd>${u.cfs}</dd>`:''}${u.shift?`<dt>Shift</dt><dd>${u.shift}</dd>`:''}${u.standby?'<dt>Standby</dt><dd>Available when off duty</dd>':''}${u.crew.length?`<dt>Crew</dt><dd>${u.crew.map(x=>`<p>${x}</p>`).join('')}</dd>`:''}${u.vehicles.length?`<dt>Vehicles</dt><dd>${u.vehicles.map(x=>`<p>${x}</p>`).join('')}</dd>`:''}</dl></div>`}
function availableActions(u,sub){if(sub)return `<div class="action-row"><button class="button-xs destructive-ghost" data-action="ungroup-one" data-id="${u.id}">Ungroup</button></div>`;return `<div class="action-row"><button class="button-xs ghost first" data-action="noop">Edit resources</button><button class="button-xs ghost" data-action="offduty" data-id="${u.id}">Set Off Duty</button>${(state.groups[u.id]||[]).length?`<button class="button-xs destructive-ghost" data-action="ungroup-all" data-id="${u.id}">Ungroup</button>`:''}<button class="button-xs" data-action="assign" data-id="${u.id}">Assign to CFS</button></div>`}
function assignedActions(u,sub){if(sub)return `<div class="action-row"><button class="button-xs destructive-ghost" data-action="ungroup-one" data-id="${u.id}">Ungroup</button></div>`;const idx=ASSIGN_STEPS.findIndex(([s])=>s===u.status);return `<div class="stepper-wrap"><div class="stepper" role="group" aria-label="Assignment status">${ASSIGN_STEPS.map(([s,label],i)=>`<button class="${i===idx?'current':i<idx?'past':''}" data-action="status" data-id="${u.id}" data-status="${s}" ${i===idx?'disabled':''}>${label}</button>`).join('')}</div><div class="stepper-divider"></div><div class="action-row"><button class="button-xs ghost first" data-action="noop">Edit resources</button><button class="button-xs destructive-ghost" data-action="cancel" data-id="${u.id}">Cancel</button>${(state.groups[u.id]||[]).length?`<button class="button-xs destructive-ghost" data-action="ungroup-all" data-id="${u.id}">Ungroup</button>`:''}<button class="button-xs" data-action="complete" data-id="${u.id}">Complete</button></div></div>`}
function item(u,{sub=false}={}){const selected=state.selectedId===u.id;const groupCount=(state.groups[u.id]||[]).length;const offline=!u.address;return `<article class="unit-item agency-${u.agencyType} ${selected?'selected':''} ${!sub?'draggable':''} ${sub?'subunit':''}" draggable="${!sub}" data-id="${u.id}"><button class="unit-header" data-action="toggle" data-id="${u.id}"><div class="unit-summary"><div class="unit-top-line"><span class="unit-name">${u.name}<span class="unit-meta"> · ${u.agency} · ${u.type}</span></span>${groupCount?`<span class="group-count">${groupCount+1}</span>`:''}${statusBadge(u)}</div>${(u.address||u.status!=='OFF_DUTY')?`<div class="unit-address ${offline?'offline':''}">${u.address||'Offline'}</div>`:''}</div>${chevron()}</button><div class="unit-expanded">${fields(u)}<div class="fade-divider"></div><div class="actions-pad">${u.tab==='assigned'?assignedActions(u,sub):availableActions(u,sub)}${sub?'<div class="subunit-helper">Controlled by top unit. Other actions are removed.</div>':''}</div></div></article>`}
function renderSubstatus(){if(state.tab!=='assigned'){els.substatus.innerHTML='';return}const opts=[['ALL','All'],...ASSIGN_STEPS];els.substatus.innerHTML=`<button class="compact-select" type="button">Filter by status <svg viewBox="0 0 24 24"><path d="m6 9 6 6 6-6"></path></svg></button><div class="status-options">${opts.map(([v,l])=>`<button class="status-chip ${state.assignedFilter===v?'active':''}" data-status-filter="${v}">${l}</button>`).join('')}</div>`}
function render(){els.tabs.querySelectorAll('.lifted-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));els.dot.style.left=state.tab==='available'?'25%':'75%';renderSubstatus();const roots=visibleRoots();els.list.innerHTML=roots.length?roots.map(u=>{const subs=(state.groups[u.id]||[]).map(unit).filter(Boolean);return `<div class="unit-group">${item(u)}${subs.length?`<div class="group-children">${subs.map(s=>item(s,{sub:true})).join('')}<div class="group-footer"><button data-action="ungroup-all" data-id="${u.id}">Ungroup all</button></div></div>`:''}</div>`}).join(''):'<div class="empty-state">No units</div>';wireDrag()}
function syncToTop(child,top){child.tab=top.tab;child.status=top.status;child.address=top.address;child.cfs=top.cfs}
function detachFromParent(id){const p=parentOf(id);if(!p)return;state.groups[p]=state.groups[p].filter(x=>x!==id);if(!state.groups[p].length)delete state.groups[p]}
function group(draggedId,targetId){const target=rootOf(targetId);if(draggedId===target||parentOf(draggedId)===target)return;const dragged=unit(draggedId),top=unit(target);if(!dragged||!top||dragged.tab!==top.tab)return;detachFromParent(draggedId);const carried=[...(state.groups[draggedId]||[])];delete state.groups[draggedId];state.groups[target]||=[];[draggedId,...carried].forEach(id=>{if(id!==target&&!state.groups[target].includes(id)){state.groups[target].push(id);syncToTop(unit(id),top)}});state.selectedId=null;audit(`${dragged.name} became a sub-unit of ${top.name}`);showToast(`${dragged.name} grouped under ${top.name}`);render()}
function fallback(u){delete u.cfs;if(u.fallback==='STANDBY'){u.tab='available';u.status='STANDBY';u.address='Fire Station 1'}else{u.tab='available';u.status='ACTIVE';u.address=u.address||'Current location'}}
function ungroupOne(id){const p=parentOf(id);if(!p)return;detachFromParent(id);fallback(unit(id));audit(`${unit(id).name} ungrouped from ${unit(p).name}`);showToast(`${unit(id).name} ungrouped`);render()}
function ungroupAll(root){const subs=[...(state.groups[root]||[])];subs.forEach(id=>fallback(unit(id)));delete state.groups[root];audit(`${unit(root).name}: all sub-units ungrouped`);showToast('Group ungrouped');render()}
function assign(rootId){const root=rootOf(rootId),top=unit(root),subs=state.groups[root]||[];members(root).forEach(id=>{const u=unit(id);u.tab='assigned';u.status='ASSIGNED';u.cfs='CFS2507027';u.address='440 9th St'});state.tab='assigned';state.selectedId=root;const text=subs.length?`${top.name} with sub-unit${subs.length>1?'s':''} ${subs.map(id=>unit(id).name).join(', ')} was assigned to CFS2507027`:`${top.name} was assigned to CFS2507027`;audit(text);showToast('Assigned to CFS2507027');render()}
function cascade(id,status){const root=rootOf(id);members(root).forEach(mid=>{const u=unit(mid);u.tab='assigned';u.status=status;u.cfs='CFS2507027';u.address='440 9th St'});audit(`${unit(root).name} group status → ${STATUS_LABEL[status]}`);render()}
function complete(id){const root=rootOf(id);members(root).forEach(mid=>{const u=unit(mid);u.tab='available';u.status='ACTIVE';delete u.cfs;u.address=u.id==='1002'?'Fire Station 1':u.address});state.tab='available';state.selectedId=root;audit(`${unit(root).name} group completed and moved to Available`);showToast('Group moved to Available');render()}
function cancelAssignment(id){const root=rootOf(id);members(root).forEach(mid=>{const u=unit(mid);u.tab='available';u.status='ACTIVE';delete u.cfs});state.tab='available';state.selectedId=root;audit(`${unit(root).name} group assignment canceled`);render()}
function setOffDuty(id){const root=rootOf(id);members(root).forEach(mid=>{const u=unit(mid);u.status='OFF_DUTY';u.address=''});audit(`${unit(root).name} group set Off Duty`);render()}
function wireDrag(){els.list.querySelectorAll('.unit-item.draggable').forEach(el=>{el.addEventListener('dragstart',e=>{state.dragId=el.dataset.id;el.classList.add('dragging');e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',state.dragId)});el.addEventListener('dragend',()=>{state.dragId=null;document.querySelectorAll('.dragging,.drop-target').forEach(x=>x.classList.remove('dragging','drop-target'))});el.addEventListener('dragover',e=>{if(!state.dragId||state.dragId===el.dataset.id)return;e.preventDefault();el.classList.add('drop-target')});el.addEventListener('dragleave',()=>el.classList.remove('drop-target'));el.addEventListener('drop',e=>{e.preventDefault();el.classList.remove('drop-target');const dragged=state.dragId||e.dataTransfer.getData('text/plain');if(dragged)group(dragged,el.dataset.id)})})}
els.list.addEventListener('click',e=>{const c=e.target.closest('[data-action]');if(!c)return;const {action,id,status}=c.dataset;if(action==='toggle'){state.selectedId=state.selectedId===id?null:id;render()}else if(action==='ungroup-one')ungroupOne(id);else if(action==='ungroup-all')ungroupAll(id);else if(action==='assign')assign(id);else if(action==='status')cascade(id,status);else if(action==='complete')complete(id);else if(action==='cancel')cancelAssignment(id);else if(action==='offduty')setOffDuty(id)});
els.tabs.addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(!b)return;state.tab=b.dataset.tab;state.selectedId=null;render()});els.search.addEventListener('input',e=>{state.search=e.target.value;render()});els.substatus.addEventListener('click',e=>{const b=e.target.closest('[data-status-filter]');if(!b)return;state.assignedFilter=b.dataset.statusFilter;render()});
els.filterTrigger.addEventListener('click',()=>{const open=!els.filterPopover.hidden;els.filterPopover.hidden=open;els.filterTrigger.setAttribute('aria-expanded',String(!open))});els.filterPopover.addEventListener('click',e=>{const b=e.target.closest('[data-agency]');if(!b)return;state.agency=b.dataset.agency;els.filterPopover.querySelectorAll('.filter-row').forEach(x=>x.classList.toggle('active',x===b));els.filterCount.textContent=state.agency==='all'?'0':'1';els.filterCount.classList.toggle('hidden',state.agency==='all');els.filterPopover.hidden=true;render()});document.addEventListener('click',e=>{if(!els.filterPopover.hidden&&!e.target.closest('.filter-trigger')&&!e.target.closest('.filters-popover'))els.filterPopover.hidden=true});
render();
